# Generated by Django 6.0 on 2025-12-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_login_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
